name: Hello World

on:
  push:
    branches:
      - main
jobs:
  hello-actions:
    runs-on: ubuntu-latest
    steps:
      - name: print the text
        run: echo "hello-GitHub Actions"
  namaste:
    runs-on: ubuntu-latest
    steps:
      - name: prin the char
        run: echo "print the char of vinod"
      - name: linux command
        run: ls
